services:
  backend:
    build: ./server
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./server:/app
    command: npm start  # or node index.js, depending on your package.json

  frontend:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - backend